extends: capitalization
message: "'%s' should use sentence-style capitalization."
link: 'https://github.com/DataDog/documentation/blob/master/CONTRIBUTING.md#headers'
level: warning
scope: heading
match: $sentence
exceptions:
  - Agent
  - Azure
  - CLI
  - Code
  - Cosmos
  - Docker
  - Emmet
  - I
  - Kubernetes
  - Linux
  - macOS
  - MongoDB
  - REPL
  - TypeScript
  - URLs
  - Windows
